apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: arbeidsgiver
  name: tag-dokgen
  namespace: {{{namespace}}}
spec:
  image: {{ image }}
  port: 8080
  team: arbeidsgiver
  liveness:
    path: /actuator/info
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  ingresses:
    - {{{ingress}}}
  env:
    - name: APP_VERSION
      value: {{ image }}
    - name: APP_TEAM
      value: arbeidsgiver