apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: permittering-og-nedbemanning
  name: permittering-dokgen
  namespace: permittering-og-nedbemanning
spec:
  image: {{ image }}
  ingresses:
    - https://permittering-dokgen.intern.dev.nav.no
  liveness:
    path: /actuator/info
  readiness:
    path: /actuator/health
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 1
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: permitteringsskjema-api
