name: Deploy til dev
on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: permittering-og-nedbemanning

      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          TEAM: permittering-og-nedbemanning
          CLUSTER: dev-gcp
          RESOURCE: nais-dev-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.docker-push.outputs.image }}
