name: Deploy til dev-fss
on:
  repository_dispatch:
    types: [deploy-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      
jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Sett variabler
        run: |
           echo "TAG=$(echo ${{ github.event.client_payload.slash_command.arg1 }} | cut -c16-22)" >> $GITHUB_ENV

      - name: Sjekk ut kode
        uses: actions/checkout@v1
        with:
          ref: ${{ env.TAG }}
    
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: arbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          REF: ${{ env.TAG }}
          VERSION: $IMAGE
          
      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: '>deploy ${{ github.event.client_payload.slash_command.args }} feilet'})
            github.issues.addLabels({...issue, labels: ['deployment-failed','dev-fss']})
   
      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.issues.createComment({...issue,
                                    body: '>deploy ${{ github.event.client_payload.slash_command.args }} var OK'})
            github.issues.addLabels({...issue, labels: ['deployment','dev-fss']})
   
