name: Deployment pipeline

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Hent tag
        run: echo "TAG=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Bygg, tag og push Docker image
        run: |
          docker build --tag $IMAGE .
          echo ${{ secrets.GHCR_PUSH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_PUSH_USERNAME }} --password-stdin
          docker push $IMAGE

      - name: Deploy til labs-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/labs-gcp.json
          VERSION: $IMAGE

      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          VERSION: $IMAGE

      - name: Deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/prod-fss.json
          VERSION: $IMAGE
