name: Deployment prod og dev

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: "read"
  id-token: "write"

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: permittering-og-nedbemanning
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          TEAM: permittering-og-nedbemanning
          CLUSTER: dev-gcp
          RESOURCE: nais-dev-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.docker-push.outputs.image }}

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          TEAM: permittering-og-nedbemanning
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.docker-push.outputs.image }}
