name: Deployment pipeline

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: dev-fss
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Hent tag
        run: echo "TAG=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Bygg, tag og push Docker image
        run: |
          docker build --tag ${IMAGE}
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}   
    
      - name: Deploy to Preprod
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: arbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          VERSION: ${IMAGE}

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: arbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/prod-fss.json
          VERSION: ${IMAGE}
