name: Deployment pipeline

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Logg inn i GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg, tag og push Docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
 
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          VERSION: $IMAGE

      - name: Deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamloennskomp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/prod-fss.json
          VERSION: $IMAGE
