name: Deployment pipeline

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: dev-fss
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/tag-dokgen
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Hent tag
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"
        
      - name: Lag image-navn
        run: echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"
        
      - name: Bygg, tag og push Docker image  
        run: |
          docker build --tag ${IMAGE} --tag ${IMAGE_BASE}:latest .
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE_BASE}   
    
      - name: Deploy to Preprod
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: teamtag
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator-gha.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          VERSION: ${IMAGE}
