name: Verify and test all branches

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: dev-fss
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/tag-dokgen
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Test med up.sh
        run: chmod +x *.sh && ./up.sh
